# Generated by Django 2.2 on 2019-06-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='app',
            field=models.CharField(choices=[('ma', 'mainapp'), ('ca', 'catalogapp')], default='ma', max_length=2, verbose_name='Приложение'),
        ),
    ]
