# Generated by Django 2.2 on 2019-06-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190613_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='path',
            field=models.CharField(max_length=255, unique=True, verbose_name='Путь'),
        ),
    ]
