# Generated by Django 2.2 on 2019-06-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190613_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункты меню', 'verbose_name_plural': 'Пункты меню'},
        ),
    ]
