# Generated by Django 2.2 on 2019-06-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190613_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование слайдера')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='', verbose_name='Фоновое изображение')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка слайда')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Slider', verbose_name='Слайдер')),
            ],
        ),
    ]
