# Generated by Django 2.2 on 2019-06-12 02:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование бренда')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование категории')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='Идентификатор категории')),
                ('slug', models.SlugField(default='', max_length=128, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogapp.Category', verbose_name='Родитесльская категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование страны')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('slug', models.SlugField(default='', max_length=128, unique=True)),
                ('key', models.CharField(max_length=30, verbose_name='Идентификатор товара')),
                ('vendor', models.CharField(blank=True, max_length=30, verbose_name='Артикул товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена товара')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Старая цена товара')),
                ('image', models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products', verbose_name='Изображение товара')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogapp.Brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.Category', verbose_name='Категория товара')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogapp.Country', verbose_name='Страна производитель')),
            ],
        ),
    ]
