# Generated by Django 2.2 on 2019-06-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес склада')),
                ('key', models.PositiveSmallIntegerField(verbose_name='Идентификатор склада')),
                ('info', models.TextField(verbose_name='Информация о складе')),
                ('latitude', models.CharField(max_length=150, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=150, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.Product', verbose_name='Товар')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.Stock', verbose_name='Склад')),
            ],
        ),
    ]
