# Generated by Django 2.2 on 2019-06-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_stock_stockproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('product', 'stock')},
        ),
    ]
