# Generated by Django 2.2 on 2019-06-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0004_auto_20190612_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
