# Generated by Django 2.2 on 2019-06-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=90, null=True, verbose_name='Эл. почта')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=90, null=True, verbose_name='Эл. почта')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=30, null=True, verbose_name='VIN')),
                ('number_or_name', models.CharField(max_length=60, verbose_name='Номер или название')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=90, null=True, verbose_name='Эл. почта')),
            ],
        ),
    ]
